# Generated by Django 5.2.9 on 2026-02-09 04:08

import django.core.validators
import django.db.models.deletion
import lectorqr.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Código interno')),
                ('id', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='El ID debe ser alfanumérico y tener máximo 10 caracteres.', regex='^[A-Za-z0-9]{1,10}$')], verbose_name='ID QR')),
                ('nombre', lectorqr.fields.EncryptedTextField(verbose_name='Nombre')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('telefono', lectorqr.fields.EncryptedTextField(blank=True, null=True, verbose_name='Teléfono')),
                ('datos_medico', lectorqr.fields.EncryptedTextField(verbose_name='Datos del médico')),
                ('informacion_clinica', lectorqr.fields.EncryptedTextField(default='', verbose_name='Información clínica')),
                ('resultado_prueba', lectorqr.fields.EncryptedTextField(default='', verbose_name='Resultado de la prueba')),
                ('fecha_de_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='images/perfil/')),
                ('foto_resultado', models.ImageField(blank=True, null=True, upload_to='results/resultado/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pacientes',
                'ordering': ['-codigo'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='lectorqr.paciente', verbose_name='Paciente Escaneado')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to=settings.AUTH_USER_MODEL, verbose_name='Escaneado por')),
            ],
            options={
                'verbose_name': 'Registro de Escaneo',
                'verbose_name_plural': 'Registros de Escaneos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
